services:
  restic:
    image: restic/restic
    container_name: restic-backup
    networks:
      - shared-network  # Attach to the bridge network
    environment:
      RESTIC_REPOSITORY: "/backup/restic-repo"
      RESTIC_PASSWORD_FILE: "/restic-password.txt/restic-password.txt"
      ##MINIO_ROOT_USER: adminuser
      #MINIO_ROOT_PASSWORD: adminpassword
    volumes:
      - ./backup:/backup
      - ./restic-password.txt:/restic-password.txt
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        
        # Create Restic backup repository if not exists
        if ! restic snapshots > /dev/null 2>&1; then
          restic init
        fi

        # Start backup loop
        while true; do
          echo "Syncing MinIO bucket to local storage..."
          

          echo "Starting Restic backup..."
          restic backup /backup/restic-repo

          echo "Backup completed. Sleeping for 5 min..."
          sleep 300
        done
        

networks:
  shared-network:
    driver: bridge  # Use the external bridge network